### PR TITLE
theis solution test for constant rate production

### PR DESCRIPTION
**Pull request by jpek15**
Tests the dirac kernel for constant rate production

### CODE REVIEW

**Comment by WilkAndy** [comment]
Hey @jpek15 - thanks for this contribution.  There are conflicts with the main branch.  I can resolve them, with a bit of effort, but almost definitely it's easier for you to do it.  Ask @cpgr to help you, otherwise you might get muddled up.  The steps are:

(1) git pull --rebase WilkAndy por_flow_initial_6740

You will get conflicts that you have to resolve.  This is the step when you start to panic.  Open up the file with conflicts in  emacs, search for all the strings "<<<<" and decide what you want to keep and what you want to throw away.  Then "git add filename".  Do this for all files with conflicts.  Then

(2) git rebase --continue

(3) The compile and run the tests, just to check

(4) git commit -a -m "merging conflicts"

(5) git push origin por_flow_initial_6740

(6) go to github and create a pull-request as usual.

**Comment by jpek15** [comment]
Dear Andy,
                 I've resolved the conflicts, corresponded with Chris, and fixed up a derivative issue. I've done a git add and git commit as suggested. (so steps 1-4). However then when I do step (5), I get 

git push origin por_flow_initial_6740 
To git@github.com:jpek15/moose.git
 ! [rejected]        por_flow_initial_6740 -> por_flow_initial_6740 (non-fast-forward)
error: failed to push some refs to 'git@github.com:jpek15/moose.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

I've tried doing a "git pull" command again, but this doesn't seem to resolve anything. Any clues?

Yours

Jonathan

**Comment by cpgr** [comment]
Somehow your local repository and your one on github have diverged. Did you 'git pull --rebase'?
You can always force your changes using 'git push -f origin por_flow_initial_6740' if you are sure you aren't going to miss something on your remote repository.

Maybe Andy has some other idea?

**Comment by WilkAndy** [comment]
Hmmm, please don't "push -f" unless you've tried everything else, otherwise it'll wipe other people's work.  This problem has only ever happened to me when i forgot to "git pull --rebase WilkAndy por_flow_initial_6740"

**Comment by WilkAndy** [comment]
Wait up, i see that now there are no conflicts with the base branch.  Are you still wanting me to merge this PR?  i'll do it when i get a chance (i'm not at work today).

**Comment by jpek15** [comment]
Fixed it now.

BTW, any clues on getting a two-phase example running? I'm fiddling around the PorousFlowMaterial2PhasePS.C

Yours

Jonathan

**Comment by jpek15** [comment]
No urgency, but you could merge this when you get a chance.

**Comment by WilkAndy** [comment]
Regarding 2-phase - if Chris hasn't made a vanGenuchten "PS" class then use the "PP" class.  The current "PS" class only has a constant capillary function (which i think is "Pc=1").  Have a look at the other 2-phase simulations (there aren't many of them):

cd porous_flow/tests
find . -name *.i | xargs grep PP_VG

that will give you all the files where the 2-phase PP vanGenuchten has been used.

**Comment by WilkAndy** [comment]
Oh, you might need quotes around the *.i, ie:

find . -name "*.i" | xargs grep PP_VG

a

**Comment by cpgr** [comment]
As it stands, PorousFlowMaterial2PhasePS.C has hard coded constant capillary pressure and is missing derivatives. I'm just finishing adding them in and making a van Genuchten form. I'll submit a pull request shortly

**Comment by cpgr** [comment]
Zing. Beaten by Andy by one minute!

**Comment by WilkAndy** [comment]
Jonathon - do you could document the theis stuff in doc/tests/theis.tex ?

a

**Comment by jpek15** [comment]
I'll have a go at this.

**Pull request merged**
